Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Not Found: /store/product/
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /himalayandelight/
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Internal Server Error: /himalayandelight/favourites/
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `foodItem.name` is not valid for model `Favourite` in `fooditem.serializers.FavouriteSerializer`.
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Internal Server Error: /himalayandelight/favourites/
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `foodItem..name` is not valid for model `Favourite` in `fooditem.serializers.FavouriteSerializer`.
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Not Found: /himalayandelight/
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Invalid HTTP_HOST header: '10.0.2.2:8000'. You may need to add '10.0.2.2' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.0.2.2:8000'. You may need to add '10.0.2.2' to ALLOWED_HOSTS.
Bad Request: /himalayandelight/favourites
Invalid HTTP_HOST header: '10.0.2.2:8000'. You may need to add '10.0.2.2' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.0.2.2:8000'. You may need to add '10.0.2.2' to ALLOWED_HOSTS.
Bad Request: /himalayandelight/favourites
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\himalayanDelightServer\settings\dev.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Not Found: /himalayandelight/
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Not Found: /himalayandelight/
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /himalayandelight/favourites11
Internal Server Error: /himalayandelight/favourites/11
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via DELETE, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining DELETE data. Change your form to point to 10.0.2.2:8000/himalayandelight/favourites/11/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Not Found: /himalayandelight/favourites/11/
Not Found: /himalayandelight/favourites/11/
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /favourites/11/
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /favourites/11/
Not Found: /himalayandelight/favourites/11/
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\himalayanDelightServer\settings\dev.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\models.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /himalayandelight/recommendation/
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\admin.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
Calling all object from fooditem
Internal Server Error: /himalayandelight/favourites
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 10.0.2.2:8000/himalayandelight/favourites/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Bad Request: /himalayandelight/favourites/
Internal Server Error: /himalayandelight/favourites
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 10.0.2.2:8000/himalayandelight/favourites/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\urls.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /himalayandelight/favourites/
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\urls.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Bad Request: /himalayandelight/favourites/
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\serializers.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Internal Server Error: /himalayandelight/favourites/
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py", line 59, in create
    favourite = Favourite.objects.create(food_item=food_item)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Favourite() got unexpected keyword arguments: 'food_item'
Internal Server Error: /himalayandelight/favourites/
Traceback (most recent call last):
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py", line 59, in create
    favourite = Favourite.objects.create(food_item=food_item)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ronis\.virtualenvs\himalayanDelightServer-rHv5xXY_\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Favourite() got unexpected keyword arguments: 'food_item'
C:\Users\ronis\OneDrive\Desktop\himalayanDelightServer\fooditem\views.py changed, reloading.
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Watching for file changes with StatReloader
Calling all object from fooditem
Not Found: /
Not Found: /favicon.ico
Not Found: /recommendation/
Watching for file changes with StatReloader
Calling all object from fooditem
